CREATE TABLE skill_categories (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE skills (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    category_id BIGINT NOT NULL REFERENCES skill_categories (id),
    UNIQUE (category_id, name)
);

INSERT INTO skill_categories (name) VALUES
    ('Music'), ('Languages'), ('Programming'), ('Cooking'), ('Fitness');

INSERT INTO skills (name, category_id)
SELECT s.name, c.id
FROM (VALUES
    ('Guitar', 'Music'),
    ('Piano', 'Music'),
    ('Singing', 'Music'),
    ('Drums', 'Music'),
    ('Music Production', 'Music'),
    ('Spanish', 'Languages'),
    ('French', 'Languages'),
    ('Irish', 'Languages'),
    ('German', 'Languages'),
    ('Japanese', 'Languages'),
    ('Java', 'Programming'),
    ('Python', 'Programming'),
    ('JavaScript', 'Programming'),
    ('SQL', 'Programming'),
    ('Web Design', 'Programming'),
    ('Baking', 'Cooking'),
    ('Meal Prep', 'Cooking'),
    ('Italian Cuisine', 'Cooking'),
    ('Vegetarian Cooking', 'Cooking'),
    ('Cocktail Making', 'Cooking'),
    ('Yoga', 'Fitness'),
    ('Running', 'Fitness'),
    ('Weight Training', 'Fitness'),
    ('Climbing', 'Fitness'),
    ('Swimming', 'Fitness')
) AS s (name, category)
JOIN skill_categories c ON c.name = s.category;